name: tableauPublicAutorefresh

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * *'

jobs:
  tableau-public-autorefresh:
    name: Tableau Public Auto-refresh
    runs-on: ubuntu-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GOOGLE_AUTHENTICATION_CREDENTIALS: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS }}
      RENV_PATHS_ROOT: ~/.local/share/renv
      RENV_VERSION: "0.17.3"
    
    steps:
      #- uses: actions/checkout@v2
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
      
      - name: Install libcurl and libssl on Linux
        run: 'sudo apt-get -y install libcurl4-openssl-dev'
        shell: bash
      
      #- name: Install CRAN packages
      #  run: Rscript -e 'install.packages(c("remotes", "googledrive", "purrr", "ggplot2"))'
      
      - name: renv package cache
        id: cache-renv
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-${{ matrix.r-version }}-${{ hashFiles('**/renv.lock') }}

      # Use renv to manage package installation
      - name: Install and activate renv
        run: |
          install.packages("renv@${{ env.RENV_VERSION }}")
          renv::activate()
        shell: Rscript {0}

      # Will automatically look for renv.lock in the root of the project
      - name: Install dependencies
        run: renv::restore()
        shell: Rscript {0}      
      
      - name: Run prepData script
        run: |
          source('R/prepData.R')
        shell: Rscript {0}